services:
  zoo1:
    image: zookeeper:3.9
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_STANDALONE_ENABLED: false
      ZOO_AUTOPURGE_PURGEINTERVAL: 1

  zoo2:
    image: zookeeper:3.9
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_STANDALONE_ENABLED: false
      ZOO_AUTOPURGE_PURGEINTERVAL: 1

  zoo3:
    image: zookeeper:3.9
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_STANDALONE_ENABLED: false
      ZOO_AUTOPURGE_PURGEINTERVAL: 1

  zk-ui:
    image: elkozmon/zoonavigator:1.1.3
    restart: unless-stopped
    environment:
      HTTP_PORT: 9000
    network_mode: host

networks:
  zk-private-network:
