name: Release

on:
  pull_request:
    types: [closed]
    paths:
      - '.github/version'

jobs:
  release:
    runs-on: ubuntu-latest
    name: release
    if: ${{github.event.pull_request.merged == true}}

    steps:
      - name: Read version from descriptor
        id: read_version
        run: |
          VERSION=$(cat .github/version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Configure Git author
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: ${{ env.VERSION }}
            release_name: ${{ env.VERSION }}
            draft: false
            prerelease: false

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...
