name: Release

on:
  pull_request:
    types: [closed]
    paths:
      - '.github/version.env'

jobs:
  release:
    runs-on: ubuntu-latest
    name: release
    if: ${{ github.event.pull_request.merged == true }}

    steps:
      - uses: actions/checkout@v2

      - name: Read version from descriptor
        id: read_version
        run: |
          cat .github/version.env >> $GITHUB_ENV

      - name: Configure Git author
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@latest
        env:
            GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
            tag_name: ${{ env.VERSION }}
            release_name: ${{ env.VERSION }}
            body: ${{ env.DESCRIPTION }}
            draft: false
            prerelease: false
